apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-deployment
  labels:
    app: payments
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - name: payments
        image: 337112169365.dkr.ecr.ap-northeast-3.amazonaws.com/sb3-u2-blossom/payments-api:latest
        ports:
        - containerPort: 3005
        env:
        - name: PORT
          value: "3005"
        - name: DB_HOST
          value: "sb3-u2-aurora.cluster-cf2o8qwgm7mv.ap-northeast-3.rds.amazonaws.com"
        - name: DB_READ_HOST
          value: "sb3-u2-aurora.cluster-ro-cf2o8qwgm7mv.ap-northeast-3.rds.amazonaws.com"
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "Admin1234!"
        - name: DB_NAME
          value: "blossom"
        - name: ORDER_API_URL
          value: "http://orders-service"
        - name: REDIS_HOST
          value: "sb3-u2-redis.uzxf7b.ng.0001.apn3.cache.amazonaws.com"
        - name: REDIS_READER_HOST
          value: "sb3-u2-redis-ro.uzxf7b.ng.0001.apn3.cache.amazonaws.com"
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: payments-service
  labels:
    app: payments
spec:
  type: ClusterIP
  selector:
    app: payments
  ports:
  - port: 80
    targetPort: 3005
