apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
  labels:
    app: cart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart
        image: 337112169365.dkr.ecr.ap-northeast-2.amazonaws.com/blossom/cart-api:latest
        ports:
        - containerPort: 3004
        env:
        - name: PORT
          value: "3004"
        - name: DB_HOST
          value: "sb3-u1-aurora.cluster-cpuskg4g6hoy.ap-northeast-2.rds.amazonaws.com"
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "Admin1234!"
        - name: DB_NAME
          value: "blossom"
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  labels:
    app: cart
spec:
  type: ClusterIP
  selector:
    app: cart
  ports:
  - port: 80
    targetPort: 3004
