apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: 337112169365.dkr.ecr.ap-northeast-3.amazonaws.com/sb3-u2-blossom/order-api:5329ac5d169626a2b0913fa06a2c4fd1b751ebc5
        ports:
        - containerPort: 3003
        env:
        - name: PORT
          value: "3003"
        - name: DB_HOST
          value: "sb3-u2-aurora.cluster-cf2o8qwgm7mv.ap-northeast-3.rds.amazonaws.com"
        - name: DB_READ_HOST
          value: "sb3-u2-aurora.cluster-ro-cf2o8qwgm7mv.ap-northeast-3.rds.amazonaws.com"
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "Admin1234!"
        - name: DB_NAME
          value: "blossom"
        - name: PRODUCT_API_URL
          value: "http://product-service"
        - name: AWS_REGION
          value: "ap-northeast-3"
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
  labels:
    app: order
spec:
  type: ClusterIP
  selector:
    app: order
  ports:
  - port: 80
    targetPort: 3003
