apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: 337112169365.dkr.ecr.ap-northeast-2.amazonaws.com/blossom/order-api:latest
        ports:
        - containerPort: 3003
        env:
        - name: PORT
          value: "3004"
        - name: DB_HOST
          value: "sb3-u1-aurora.cluster-cpuskg4g6hoy.ap-northeast-2.rds.amazonaws.com"
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "Admin1234!"
        - name: DB_NAME
          value: "blossom"
        - name: PRODUCT_API_URL
          value: "http://product-service"
        - name: AWS_REGION
          value: "ap-northeast-2"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order
spec:
  type: ClusterIP
  selector:
    app: order
  ports:
  - port: 80
    targetPort: 3003
