apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-deployment
  labels:
    app: payments
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - name: payments
        image: 337112169365.dkr.ecr.ap-northeast-2.amazonaws.com/blossom/payments-api:latest
        ports:
        - containerPort: 3005
        env:
        - name: PORT
          value: "3005"
        - name: DB_HOST
          value: "sb3-u1-aurora.cluster-cpuskg4g6hoy.ap-northeast-2.rds.amazonaws.com"
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "Admin1234!"
        - name: DB_NAME
          value: "blossom"
        - name: ORDER_API_URL
          value: "http://orders-service"
        - name: REDIS_HOST
          value: "${REDIS_ENDPOINT}"
        - name: REDIS_PORT
          value: "6379"
        
---
apiVersion: v1
kind: Service
metadata:
  name: payments-service
  labels:
    app: payments
spec:
  type: ClusterIP
  selector:
    app: payments
  ports:
  - port: 80
    targetPort: 3005
