apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  labels:
    app: product
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: 337112169365.dkr.ecr.ap-northeast-2.amazonaws.com/blossom/product-api:latest
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          value: "3002"
        - name: DB_HOST
          value: "sb3-u1-aurora.cluster-cpuskg4g6hoy.ap-northeast-2.rds.amazonaws.com"
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "Admin1234!"
        - name: DB_NAME
          value: "blossom"
        - name: AWS_REGION
          value: "ap-northeast-2"
        - name: S3_BUCKET
          value: "sb3-u4-eks-test"
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product
spec:
  type: ClusterIP
  selector:
    app: product
  ports:
  - port: 80
    targetPort: 3002
