apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  labels:
    app: user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: 337112169365.dkr.ecr.ap-northeast-2.amazonaws.com/blossom/user-api:latest
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: DB_HOST
          value: "sb3-u1-aurora.cluster-cpuskg4g6hoy.ap-northeast-2.rds.amazonaws.com"
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "Admin1234!"
        - name: DB_NAME
          value: "blossom"
        - name: REDIS_HOST
          value: "sb3-u1-redis-ro.8yu9pt.ng.0001.apn2.cache.amazonaws.com:6379"
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  labels:
    app: user
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
  - port: 80
    targetPort: 3001
