apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
  labels:
    app: product
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: 337112169365.dkr.ecr.ap-northeast-3.amazonaws.com/sb3-u2-blossom/product-api:5329ac5d169626a2b0913fa06a2c4fd1b751ebc5
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          value: "3002"
        - name: DB_HOST
          value: "sb3-u2-aurora.cluster-cf2o8qwgm7mv.ap-northeast-3.rds.amazonaws.com"
        - name: DB_READ_HOST
          value: "sb3-u2-aurora.cluster-ro-cf2o8qwgm7mv.ap-northeast-3.rds.amazonaws.com"
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "Admin1234!"
        - name: DB_NAME
          value: "blossom"
        - name: AWS_REGION
          value: "ap-northeast-3"
        - name: S3_BUCKET
          value: "sb3-u4-eks-test"
---
apiVersion: v1
kind: Service
metadata:
  name: products-service
  labels:
    app: product
spec:
  type: ClusterIP
  selector:
    app: product
  ports:
  - port: 80
    targetPort: 3002
