apiVersion: apps/v1
kind: Deployment
metadata:
  name: lex-api-deployment
  labels:
    app: lex-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lex-api
  template:
    metadata:
      labels:
        app: lex-api
    spec:
      containers:
      - name: lex-api
        image: 337112169365.dkr.ecr.us-east-1.amazonaws.com/sb3-u2-blossom/lex-api:latest
        ports:
        - containerPort: 3006
        env:
        - name: PORT
          value: "3006"
        - name: DB_HOST
          value: "sb3-u2-aurora.cluster-cuv62qsm0iad.us-east-1.rds.amazonaws.com"
        - name: DB_READ_HOST
          value: "sb3-u2-aurora.cluster-ro-cuv62qsm0iad.us-east-1.rds.amazonaws.com"
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "Admin1234!"
        - name: DB_NAME
          value: "blossom"
---
apiVersion: v1
kind: Service
metadata:
  name: lex-api-service
  labels:
    app: lex-api
spec:
  type: ClusterIP
  selector:
    app: lex-api
  ports:
  - port: 80
    targetPort: 3006
