apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
  labels:
    app: product
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: 337112169365.dkr.ecr.us-east-1.amazonaws.com/sb3-u2-blossom/product-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          value: "3002"
        - name: DB_HOST
          value: "sb3-u2-aurora.cluster-cuv62qsm0iad.us-east-1.rds.amazonaws.com"
        - name: DB_READ_HOST
          value: "sb3-u2-aurora.cluster-ro-cuv62qsm0iad.us-east-1.rds.amazonaws.com"
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "Admin1234!"
        - name: DB_NAME
          value: "blossom"
---
apiVersion: v1
kind: Service
metadata:
  name: products-service
  labels:
    app: product
spec:
  type: ClusterIP
  selector:
    app: product
  ports:
  - port: 80
    targetPort: 3002
