apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  namespace: default
  labels:
    app: user
spec:
  replicas: 2
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: user
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: 337112169365.dkr.ecr.us-east-1.amazonaws.com/sb3-u2-blossom/user-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: DB_HOST
              value: sb3-u2-aurora.cluster-cuv62qsm0iad.us-east-1.rds.amazonaws.com
            - name: DB_READ_HOST
              value: sb3-u2-aurora.cluster-ro-cuv62qsm0iad.us-east-1.rds.amazonaws.com
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              value: Admin1234!
            - name: DB_NAME
              value: blossom
            - name: REDIS_HOST
              value: sb3-u2-redis.ojjs5i.ng.0001.use1.cache.amazonaws.com
            - name: REDIS_READER_HOST
              value: sb3-u2-redis-ro.ojjs5i.ng.0001.use1.cache.amazonaws.com
            - name: REDIS_PORT
              value: "6379"
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: default
  labels:
    app: user
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
    - port: 80
      targetPort: 3001
