apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts-deployment
  labels:
    app: cart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart
        image: 337112169365.dkr.ecr.ap-northeast-3.amazonaws.com/sb3-u2-blossom/cart-api:5329ac5d169626a2b0913fa06a2c4fd1b751ebc5
        ports:
        - containerPort: 3004
        env:
        - name: PORT
          value: "3004"
        - name: DB_HOST
          value: "sb3-u2-aurora.cluster-cf2o8qwgm7mv.ap-northeast-3.rds.amazonaws.com"
        - name: DB_READ_HOST
          value: "sb3-u2-aurora.cluster-ro-cf2o8qwgm7mv.ap-northeast-3.rds.amazonaws.com"
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "Admin1234!"
        - name: DB_NAME
          value: "blossom"
        - name: REDIS_HOST
          value: "sb3-u2-redis.uzxf7b.ng.0001.apn3.cache.amazonaws.com"
        - name: REDIS_READER_HOST
          value: "sb3-u2-redis-ro.uzxf7b.ng.0001.apn3.cache.amazonaws.com"
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: carts-service
  labels:
    app: cart
spec:
  type: ClusterIP
  selector:
    app: cart
  ports:
  - port: 80
    targetPort: 3004
